%YAML:1.0

# MAIN

LOG_Threshold: 0
Init_Frame_Index: 0
USE_GT_DATA: 1


# Input/Output directories and Sets
Output.Directory.LOG_DIR: "./Log/"


USE_VIDEO: 1
Calib_FX: 832.560809
Calib_FY: 832.560809
Calib_CX: 319.5
Calib_CY: 239.5
Input.Directory.Obj: "/Users/flamming/WorkSpace/ROBOT/data/cat/cat.obj"
Input.Directory.Video: "/Users/flamming/WorkSpace/ROBOT/data/cat/cat_video.avi"
Input.Directory.GroudTruth: "/Users/flamming/WorkSpace/ROBOT/data/cat/cat_gtpose.txt"
Input.Directory.DISTORTIONS: "/Users/flamming/WorkSpace/ROBOT/data/cat/distortions.txt"
VIDEO_WIDTH: 640
VIDEO_HEIGHT: 480

#CV
CV_DRAW_FRAME: 1


#IMG
IMG_PYR_NUMBER: 5
IMG_DIST_MASK_SIZE: 8

